kotlin.code.style=official
kotlin.stdlib.default.dependency=false

org.gradle.jvmargs=-Xmx768m -Dfile.encoding=UTF-8
kotlin.daemon.jvmargs=-Xmx512m
org.gradle.workers.max=2

org.jetbrains.intellij.platform.intellijPlatformCache=C:/Users/tayja/.cache/ti84-evo-intellij-platform
org.jetbrains.intellij.platform.intellijPlatformIdesCache=C:/Users/tayja/.cache/intellij-platform-ides
org.jetbrains.intellij.platform.intellijPlatformIdesCacheEnabled=true
