"""TI-Innovator Rover API supplied by calculator firmware."""

from typing import Literal, TypeAlias, overload

Number: TypeAlias = int | float
DistanceUnit: TypeAlias = Literal["units", "m", "revs"]
AngleUnit: TypeAlias = Literal["degrees", "radians", "gradians"]
RateUnit: TypeAlias = Literal["units/s", "m/s", "revs/s"]
Direction: TypeAlias = Literal["clockwise", "counter-clockwise", "CW", "CCW"]

class tiroverException(Exception): ...

@overload
def forward(distance: Number) -> None: ...
@overload
def forward(distance: Number, unit: DistanceUnit) -> None: ...
@overload
def forward(distance: Number, unit: DistanceUnit, speed: Number, rate: RateUnit) -> None: ...

@overload
def backward(distance: Number) -> None: ...
@overload
def backward(distance: Number, unit: DistanceUnit) -> None: ...
@overload
def backward(distance: Number, unit: DistanceUnit, speed: Number, rate: RateUnit) -> None: ...

@overload
def left(angle: Number) -> None: ...
@overload
def left(angle: Number, unit: AngleUnit) -> None: ...

@overload
def right(angle: Number) -> None: ...
@overload
def right(angle: Number, unit: AngleUnit) -> None: ...

def stop() -> None:
    """Stop Rover movement."""
    ...

def stop_clear() -> None:
    """Stop Rover and clear queued commands."""
    ...

def resume() -> None:
    """Resume Rover movement after a stop."""
    ...

def stay(time: Number = 30) -> None:
    """Remain at the current position for the requested time."""
    ...

def to_xy(x: Number, y: Number) -> None:
    """Drive to an absolute grid coordinate."""
    ...

def to_polar(radius: Number, theta: Number) -> None:
    """Drive to a position expressed as polar coordinates."""
    ...

def to_angle(angle: Number, unit: AngleUnit = "degrees") -> None:
    """Turn to an absolute heading."""
    ...

def forward_time(time: Number, speed: Number | None = None, rate: RateUnit = "units/s") -> None:
    """Drive forward for a duration, optionally at a requested rate."""
    ...

def backward_time(time: Number, speed: Number | None = None, rate: RateUnit = "units/s") -> None:
    """Drive backward for a duration, optionally at a requested rate."""
    ...

def ranger_measurement() -> float: ...
def ranger_time() -> float: ...
def color_measurement() -> int: ...
def red_measurement() -> int: ...
def green_measurement() -> int: ...
def blue_measurement() -> int: ...
def gray_measurement() -> int: ...
def encoders_gyro_measurement() -> list[float]: ...
def gyro_measurement() -> float: ...

def color_rgb(red: int, green: int, blue: int) -> None: ...
def color_blink(frequency: Number, time: Number) -> None: ...
def color_off() -> None: ...
def motor_left(speed: Number, time: Number = 5) -> None: ...
def motor_right(speed: Number, time: Number = 5) -> None: ...
def motors(
    left_direction: Direction,
    left_speed: Number,
    right_direction: Direction,
    right_speed: Number,
    time: Number = 5,
) -> None: ...

def waypoint_xythdrn() -> list[float]: ...
def waypoint_prev() -> list[float]: ...
def waypoint_eta() -> float: ...
def path_done() -> int: ...
def pathlist_x() -> list[float]: ...
def pathlist_y() -> list[float]: ...
def pathlist_time() -> list[float]: ...
def pathlist_heading() -> list[float]: ...
def pathlist_distance() -> list[float]: ...
def pathlist_revs() -> list[float]: ...
def pathlist_cmdnum() -> list[int]: ...
def waypoint_x() -> float: ...
def waypoint_y() -> float: ...
def waypoint_time() -> float: ...
def waypoint_heading() -> float: ...
def waypoint_distance() -> float: ...
def waypoint_revs() -> float: ...

def wait_until_done() -> None: ...

@overload
def position(x: Number, y: Number) -> None: ...
@overload
def position(x: Number, y: Number, heading: Number) -> None: ...

def grid_origin() -> None: ...
def grid_m_unit(scale: Number) -> None: ...
def path_clear() -> None: ...
def zero_gyro() -> None: ...
def disconnect_rv() -> None: ...
